### PR TITLE
Integer arithmetic

### PR DESCRIPTION
**Pull request by ForNeVeR**
Basic integer math support along with useful infrastructural changes.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
I can say that this PR is pretty much done. Mr. @rexim, last time we discussed it you were willing to review a bit of Naggum code. Wanna give this PR a try?

**Comment by rexim** [comment]
@ForNeVeR, Do I understand correctly that you've added support to invoke primitive .NET arithmetical instructions from naggum and the next step is gonna be to define more high-level functions like +, -, /, *, etc?

**Comment by ForNeVeR** [comment]
Well, that's a bit complicated. Look, `Naggum.Assembler` is a core for a low-level language. First thing you do when creating a low-level language is to define a mapping form target machine language to your low-level language constructs. Hereby I define such mapping for primitive arithmetic instructions of our chosen target machine - CLI.

This is somewhat orthogonal to calling "functions" such as `+`. I don't think that `Naggum.Assembler` will include such functions at all. All that it will do is to assemble our low-level core language to actual .NET binaries.

I still don't know whether it will expand macros (or we'll create another layer for them) and how it will interact with our current high-level `Naggum.Compiler` language.

And, yeah, regarding your question. That `+` function may conceptually be defined as macro (expanding to the low-level instruction set I've created with this PR) or a real function (not _expanded_, but _compiled to_ that low-level instruction set). Either way, `+` function is totally impossible without that arithmetic instructions, but currently I am not able to tell you how or when we'll have an ability to implement such functions in Naggum.

Honestly say, I even have no definition of _function_ currently.

But you'll be able to define a _method_ named, say, `Add`, and write it in terms of these new instructions, and even maybe call it using our `(call ...)` syntax.

**Comment by rexim** [comment]
@ForNeVeR that means I understood everything correctly from your change. I approve the PR.

**Comment by ForNeVeR** [comment]
Thanks for the review.

**Pull request merged**
