### PR TITLE
Line endings conversion

### LINKED ISSUE #34: Line format conversion
We should convert all of the line endings in out code to the standard `\n` format. I've found that multiple files don't use it.

### PR DESCRIPTION
**Pull request by ForNeVeR**
This PR will close #34. We'll use only standard line ending format in future.

### CODE REVIEW

**Comment by rexim** [comment]
Best change ever! Hope it will make our `git-blame` even more prettier!

**Comment by ForNeVeR** [comment]
It will make contributing and core review easier, because otherwise these changes anyway would pollute our repository inside any random patches (check https://github.com/codingteam/naggum/pull/30/files#diff-0a20fc0b7ff77a3a7944ca5177f2e86fL1 as an example). So this change should be made as early as possible. Your irony is inappropriate here.

**Comment by rexim** [comment]
I'm always serious in PRs. Your remark is inappropriate here. Goat confirms. :goat:

**Comment by ForNeVeR** [comment]
Now I'm decoupled enough from the state of mind in which I've created this PR. The time has come, I'm starting to review it myself.

**Pull request merged**
